config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :diets
  resources :foods

end

app/models/diet.rb
class Diet < ActiveRecord::Base
	validates :name, :description, :calories, presence: true
end

app/models/food.rb
class Food < ActiveRecord::Base
  has_and_belongs_to_many :groups
  validates :name, :description, :unit, :cuantity, :calories, presence: true
 end

app/models/foods_group.rb
class FoodsGroup < ActiveRecord::Base
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :foods
  validates :name, :day, :time, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
 # before_action :set_diet, only: [:show, :edit, :update, :destroy]
  # GET /diets
  def index
    render json:  Diet.all
  end

  def create
	diet = Diet.new(diet_params)
		if diet.save 
			render json: diet, status: :created
		else
			render json: {errors: diet.errors}, status: 422
		end
  end

  def update
	diet = Diet.find(params[:id])

		if diet.update(diet_params)
			render json: diet, status: :ok
		end 	

  end

  def destroy
  		
	Diet.find(params[:id]).destroy
		head :no_content
 end

 private
  	def diet_params
		params.require(:diet).permit(:name, :description, :calories)
	end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
 # before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  def index
    render json:  Food.all
  end

  def create
	food = Food.new(food_params)
		if food.save 
			render json: food, status: :created
		else
			render json: {errors: food.errors}, status: 422
		end
  end

  def update
	food = Food.find(params[:id])

		if food.update(food_params)
			render json: food, status: :ok
		end 	

  end

  def destroy
  		
	Food.find(params[:id]).destroy
		head :no_content
 end

 private
  	def food_params
		params.require(:food).permit(:name, :description, :unit, :cuantity, :calories)
	end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
 # before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  def index
    render json:  Group.all
  end

  def create
	group = Group.new(group_params)
		if group.save 
			render json: group, status: :created
		else
			render json: {errors: group.errors}, status: 422
		end
  end

  def update
	group = Group.find(params[:id])

		if group.update(group_params)
			render json: group, status: :ok
		end 	

  end

  def destroy
  		
	Group.find(params[:id]).destroy
		head :no_content
 end

 private
  	def group_params
		params.require(:group).permit(:name, :day, :time)
	end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/diets/_form.html.erb
<%= form_for(@diet) do |f| %>
  <% if @diet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diet.errors.count, "error") %> prohibited this diet from being saved:</h2>

      <ul>
      <% @diet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.number_field :calories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diets/edit.html.erb
<h1>Editing Diet</h1>

<%= render 'form' %>

<%= link_to 'Show', @diet %> |
<%= link_to 'Back', diets_path %>

app/views/diets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Diets</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Calories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diets.each do |diet| %>
      <tr>
        <td><%= diet.name %></td>
        <td><%= diet.description %></td>
        <td><%= diet.calories %></td>
        <td><%= link_to 'Show', diet %></td>
        <td><%= link_to 'Edit', edit_diet_path(diet) %></td>
        <td><%= link_to 'Destroy', diet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diet', new_diet_path %>

app/views/diets/new.html.erb
<h1>New Diet</h1>

<%= render 'form' %>

<%= link_to 'Back', diets_path %>

app/views/diets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @diet.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @diet.description %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @diet.calories %>
</p>

<%= link_to 'Edit', edit_diet_path(@diet) %> |
<%= link_to 'Back', diets_path %>

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :unit %><br>
    <%= f.text_field :unit %>
  </div>
  <div class="field">
    <%= f.label :cuantity %><br>
    <%= f.number_field :cuantity %>
  </div>
  <div class="field">
    <%= f.label :calories %><br>
    <%= f.number_field :calories %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Unit</th>
      <th>Cuantity</th>
      <th>Calories</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.description %></td>
        <td><%= food.unit %></td>
        <td><%= food.cuantity %></td>
        <td><%= food.calories %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @food.unit %>
</p>

<p>
  <strong>Cuantity:</strong>
  <%= @food.cuantity %>
</p>

<p>
  <strong>Calories:</strong>
  <%= @food.calories %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/groups/_form.html.erb
<%= form_for(@group) do |f| %>
  <% if @group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% @group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :day %><br>
    <%= f.text_field :day %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Day</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= group.day %></td>
        <td><%= group.time %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form' %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<p>
  <strong>Day:</strong>
  <%= @group.day %>
</p>

<p>
  <strong>Time:</strong>
  <%= @group.time %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppTest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>